WarlockSpells = {
  [1] = {
    { name = "Immolate", school = "Destruction", level = 1, icon = "Interface\\Icons\\Spell_Fire_Immolation", subText = "Rank 1" },
  },
  [4] = {
    { name = "Corruption",        school = "Affliction", level = 4, icon = "Interface\\Icons\\Spell_Shadow_AbominationExplosion", subText = "Rank 1" },
    { name = "Curse of Weakness", school = "Affliction", level = 4, icon = "Interface\\Icons\\Spell_Shadow_CurseOfMannoroth",     subText = "" },
  },
  [6] = {
    { name = "Life Tap",    school = "Affliction",  level = 6, icon = "Interface\\Icons\\Spell_Shadow_BurningSpirit", subText = "Rank 1" },
    { name = "Shadow Bolt", school = "Destruction", level = 6, icon = "Interface\\Icons\\Spell_Shadow_ShadowBolt",    subText = "Rank 2" },
  },
  [8] = {
    { name = "Curse of Agony", school = "Affliction", level = 8, icon = "Interface\\Icons\\Spell_Shadow_CurseOfSargeras", subText = "Rank 1" },
    { name = "Fear",           school = "Affliction", level = 8, icon = "Interface\\Icons\\Spell_Shadow_Possession",      subText = "Rank 1" },
  },
  [10] = {
    { name = "Drain Soul",                 school = "Affliction",  level = 10, icon = "Interface\\Icons\\Spell_Shadow_Haunting",     subText = "Rank 1" },
    { name = "Create Healthstone (Minor)", school = "Demonology",  level = 10, icon = "Interface\\Icons\\INV_Stone_04",              subText = "" },
    { name = "Demon Armor",                school = "Demonology",  level = 10, icon = "Interface\\Icons\\Spell_Shadow_RagingScream", subText = "Rank 2" },
    { name = "Immolate",                   school = "Destruction", level = 10, icon = "Interface\\Icons\\Spell_Fire_Immolation",     subText = "Rank 2" },
  },
  [12] = {
    { name = "Health Funnel", school = "Demonology",  level = 12, icon = "Interface\\Icons\\Spell_Shadow_LifeDrain",  subText = "Rank 1" },
    { name = "Shadow Bolt",   school = "Destruction", level = 12, icon = "Interface\\Icons\\Spell_Shadow_ShadowBolt", subText = "Rank 3" },
  },
  [14] = {
    { name = "Corruption",            school = "Affliction", level = 14, icon = "Interface\\Icons\\Spell_Shadow_AbominationExplosion", subText = "Rank 2" },
    { name = "Curse of Recklessness", school = "Affliction", level = 14, icon = "Interface\\Icons\\Spell_Shadow_UnholyStrength",       subText = "Rank 1" },
    { name = "Drain Life",            school = "Affliction", level = 14, icon = "Interface\\Icons\\Spell_Shadow_LifeDrain02",          subText = "Rank 1" },
  },
  [16] = {
    { name = "Life Tap",        school = "Affliction", level = 16, icon = "Interface\\Icons\\Spell_Shadow_BurningSpirit", subText = "Rank 2" },
    { name = "Unending Breath", school = "Demonology", level = 16, icon = "Interface\\Icons\\Spell_Shadow_DemonBreath",   subText = "" },
  },
  [18] = {
    { name = "Curse of Agony",           school = "Affliction",  level = 18, icon = "Interface\\Icons\\Spell_Shadow_CurseOfSargeras", subText = "Rank 2" },
    { name = "Create Soulstone (Minor)", school = "Demonology",  level = 18, icon = "Interface\\Icons\\Spell_Shadow_SoulGem",         subText = "" },
    { name = "Searing Pain",             school = "Destruction", level = 18, icon = "Interface\\Icons\\Spell_Fire_SoulBurn",          subText = "Rank 1" },
  },
  [20] = {
    { name = "Demon Armor",         school = "Demonology",  level = 20, icon = "Interface\\Icons\\Spell_Shadow_RagingScream", subText = "Rank 3" },
    { name = "Health Funnel",       school = "Demonology",  level = 20, icon = "Interface\\Icons\\Spell_Shadow_LifeDrain",    subText = "Rank 2" },
    { name = "Ritual of Summoning", school = "Demonology",  level = 20, icon = "Interface\\Icons\\Spell_Shadow_Twilight",     subText = "" },
    { name = "Immolate",            school = "Destruction", level = 20, icon = "Interface\\Icons\\Spell_Fire_Immolation",     subText = "Rank 3" },
    { name = "Rain of Fire",        school = "Destruction", level = 20, icon = "Interface\\Icons\\Spell_Shadow_RainOfFire",   subText = "Rank 1" },
    { name = "Shadow Bolt",         school = "Destruction", level = 20, icon = "Interface\\Icons\\Spell_Shadow_ShadowBolt",   subText = "Rank 4" },
  },
  [22] = {
    { name = "Drain Life",                  school = "Affliction", level = 22, icon = "Interface\\Icons\\Spell_Shadow_LifeDrain02", subText = "Rank 2" },
    { name = "Create Firestone",            school = "Demonology", level = 22, icon = "Interface\\Icons\\INV_Ammo_FireTar",         subText = "" },
    { name = "Create Healthstone (Lesser)", school = "Demonology", level = 22, icon = "Interface\\Icons\\INV_Stone_04",             subText = "" },
    { name = "Eye of Kilrogg",              school = "Demonology", level = 22, icon = "Interface\\Icons\\Spell_Shadow_EvilEye",     subText = "Summon" },
  },
  [24] = {
    { name = "Corruption",   school = "Affliction",  level = 24, icon = "Interface\\Icons\\Spell_Shadow_AbominationExplosion", subText = "Rank 3" },
    { name = "Drain Mana",   school = "Affliction",  level = 24, icon = "Interface\\Icons\\Spell_Shadow_SiphonMana",           subText = "Rank 1" },
    { name = "Drain Soul",   school = "Affliction",  level = 24, icon = "Interface\\Icons\\Spell_Shadow_Haunting",             subText = "Rank 2" },
    { name = "Sense Demons", school = "Demonology",  level = 24, icon = "Interface\\Icons\\Spell_Shadow_Metamorphosis",        subText = "" },
    { name = "Shadowburn",   school = "Destruction", level = 24, icon = "Interface\\Icons\\Spell_Shadow_ScourgeBuild",         subText = "Rank 2" },
  },
  [26] = {
    { name = "Curse of Tongues",           school = "Affliction",  level = 26, icon = "Interface\\Icons\\Spell_Shadow_CurseOfTounges",           subText = "Rank 1" },
    { name = "Life Tap",                   school = "Affliction",  level = 26, icon = "Interface\\Icons\\Spell_Shadow_BurningSpirit",            subText = "Rank 3" },
    { name = "Detect Lesser Invisibility", school = "Demonology",  level = 26, icon = "Interface\\Icons\\Spell_Shadow_DetectLesserInvisibility", subText = "" },
    { name = "Searing Pain",               school = "Destruction", level = 26, icon = "Interface\\Icons\\Spell_Fire_SoulBurn",                   subText = "Rank 2" },
  },
  [28] = {
    { name = "Curse of Agony",        school = "Affliction",  level = 28, icon = "Interface\\Icons\\Spell_Shadow_CurseOfSargeras", subText = "Rank 3" },
    { name = "Curse of Recklessness", school = "Affliction",  level = 28, icon = "Interface\\Icons\\Spell_Shadow_UnholyStrength",  subText = "Rank 2" },
    { name = "Banish",                school = "Demonology",  level = 28, icon = "Interface\\Icons\\Spell_Shadow_Cripple",         subText = "Rank 1" },
    { name = "Health Funnel",         school = "Demonology",  level = 28, icon = "Interface\\Icons\\Spell_Shadow_LifeDrain",       subText = "Rank 3" },
    { name = "Shadow Bolt",           school = "Destruction", level = 28, icon = "Interface\\Icons\\Spell_Shadow_ShadowBolt",      subText = "Rank 5" },
  },
  [30] = {
    { name = "Drain Life",                school = "Affliction",  level = 30, icon = "Interface\\Icons\\Spell_Shadow_LifeDrain02",  subText = "Rank 3" },
    { name = "Create Soulstone (Lesser)", school = "Demonology",  level = 30, icon = "Interface\\Icons\\Spell_Shadow_SoulGem",      subText = "" },
    { name = "Demon Armor",               school = "Demonology",  level = 30, icon = "Interface\\Icons\\Spell_Shadow_RagingScream", subText = "Rank 4" },
    { name = "Enslave Demon",             school = "Demonology",  level = 30, icon = "Interface\\Icons\\Spell_Shadow_EnslaveDemon", subText = "Rank 1" },
    { name = "Hellfire",                  school = "Destruction", level = 30, icon = "Interface\\Icons\\Spell_Fire_Incinerate",     subText = "Rank 1" },
    { name = "Immolate",                  school = "Destruction", level = 30, icon = "Interface\\Icons\\Spell_Fire_Immolation",     subText = "Rank 4" },
    { name = "Soul Fire",                 school = "Destruction", level = 30, icon = "Interface\\Icons\\Spell_Fire_Fireball02",     subText = "Rank 1" },
  },
  [32] = {
    { name = "Curse of the Elements", school = "Affliction",  level = 32, icon = "Interface\\Icons\\Spell_Shadow_ChillTouch",   subText = "Rank 1" },
    { name = "Fear",                  school = "Affliction",  level = 32, icon = "Interface\\Icons\\Spell_Shadow_Possession",   subText = "Rank 2" },
    { name = "Create Felstone",       school = "Demonology",  level = 32, icon = "Interface\\Icons\\inv_misc_gem_felstone",     subText = "" },
    { name = "Shadow Ward",           school = "Demonology",  level = 32, icon = "Interface\\Icons\\Spell_Shadow_AntiShadow",   subText = "Rank 1" },
    { name = "Shadowburn",            school = "Destruction", level = 32, icon = "Interface\\Icons\\Spell_Shadow_ScourgeBuild", subText = "Rank 3" },
  },
  [34] = {
    { name = "Corruption",         school = "Affliction",  level = 34, icon = "Interface\\Icons\\Spell_Shadow_AbominationExplosion", subText = "Rank 4" },
    { name = "Drain Mana",         school = "Affliction",  level = 34, icon = "Interface\\Icons\\Spell_Shadow_SiphonMana",           subText = "Rank 2" },
    { name = "Create Healthstone", school = "Demonology",  level = 34, icon = "Interface\\Icons\\INV_Stone_04",                      subText = "" },
    { name = "Rain of Fire",       school = "Destruction", level = 34, icon = "Interface\\Icons\\Spell_Shadow_RainOfFire",           subText = "Rank 2" },
    { name = "Searing Pain",       school = "Destruction", level = 34, icon = "Interface\\Icons\\Spell_Fire_SoulBurn",               subText = "Rank 3" },
  },
  [36] = {
    { name = "Life Tap",      school = "Affliction",  level = 36, icon = "Interface\\Icons\\Spell_Shadow_BurningSpirit", subText = "Rank 4" },
    { name = "Health Funnel", school = "Demonology",  level = 36, icon = "Interface\\Icons\\Spell_Shadow_LifeDrain",     subText = "Rank 4" },
    { name = "Shadow Bolt",   school = "Destruction", level = 36, icon = "Interface\\Icons\\Spell_Shadow_ShadowBolt",    subText = "Rank 6" },
  },
  [38] = {
    { name = "Curse of Agony",      school = "Affliction",  level = 38, icon = "Interface\\Icons\\Spell_Shadow_CurseOfSargeras",    subText = "Rank 4" },
    { name = "Drain Life",          school = "Affliction",  level = 38, icon = "Interface\\Icons\\Spell_Shadow_LifeDrain02",        subText = "Rank 4" },
    { name = "Drain Soul",          school = "Affliction",  level = 38, icon = "Interface\\Icons\\Spell_Shadow_Haunting",           subText = "Rank 3" },
    { name = "Siphon Life",         school = "Affliction",  level = 38, icon = "Interface\\Icons\\Spell_Shadow_Requiem",            subText = "Rank 2" },
    { name = "Detect Invisibility", school = "Demonology",  level = 38, icon = "Interface\\Icons\\Spell_Shadow_DetectInvisibility", subText = "" },
    { name = "Soul Fire",           school = "Destruction", level = 38, icon = "Interface\\Icons\\Spell_Fire_Fireball02",           subText = "Rank 2" },
  },
  [40] = {
    { name = "Howl of Terror",   school = "Affliction",  level = 40, icon = "Interface\\Icons\\Spell_Shadow_DeathScream",      subText = "Rank 1" },
    { name = "Create Soulstone", school = "Demonology",  level = 40, icon = "Interface\\Icons\\Spell_Shadow_SoulGem",          subText = "" },
    { name = "Demon Armor",      school = "Demonology",  level = 40, icon = "Interface\\Icons\\Spell_Shadow_RagingScream",     subText = "Rank 5" },
    { name = "Mana Funnel",      school = "Demonology",  level = 40, icon = "Interface\\Icons\\Spell_Shadow_UnsummonBuilding", subText = "Rank 1" },
    { name = "Immolate",         school = "Destruction", level = 40, icon = "Interface\\Icons\\Spell_Fire_Immolation",         subText = "Rank 5" },
    { name = "Shadowburn",       school = "Destruction", level = 40, icon = "Interface\\Icons\\Spell_Shadow_ScourgeBuild",     subText = "Rank 4" },
  },

  [42] = {
    { name = "Curse of Recklessness", school = "Affliction",  level = 42, icon = "Interface\\Icons\\Spell_Shadow_UnholyStrength", subText = "Rank 3" },
    { name = "Death Coil",            school = "Affliction",  level = 42, icon = "Interface\\Icons\\Spell_Shadow_DeathCoil",      subText = "Rank 1" },
    { name = "Create Wrathstone",     school = "Demonology",  level = 42, icon = "Interface\\Icons\\INV_Misc_Gem_Bloodstone_02",  subText = "" },
    { name = "Shadow Ward",           school = "Demonology",  level = 42, icon = "Interface\\Icons\\Spell_Shadow_AntiShadow",     subText = "Rank 2" },
    { name = "Hellfire",              school = "Destruction", level = 42, icon = "Interface\\Icons\\Spell_Fire_Incinerate",       subText = "Rank 2" },
    { name = "Searing Pain",          school = "Destruction", level = 42, icon = "Interface\\Icons\\Spell_Fire_SoulBurn",         subText = "Rank 4" },
  },
  [44] = {
    { name = "Corruption",      school = "Affliction",  level = 44, icon = "Interface\\Icons\\Spell_Shadow_AbominationExplosion", subText = "Rank 5" },
    { name = "Curse of Shadow", school = "Affliction",  level = 44, icon = "Interface\\Icons\\Spell_Shadow_CurseOfAchimonde",     subText = "Rank 1" },
    { name = "Drain Mana",      school = "Affliction",  level = 44, icon = "Interface\\Icons\\Spell_Shadow_SiphonMana",           subText = "Rank 3" },
    { name = "Enslave Demon",   school = "Demonology",  level = 44, icon = "Interface\\Icons\\Spell_Shadow_EnslaveDemon",         subText = "Rank 2" },
    { name = "Health Funnel",   school = "Demonology",  level = 44, icon = "Interface\\Icons\\Spell_Shadow_LifeDrain",            subText = "Rank 5" },
    { name = "Shadow Bolt",     school = "Destruction", level = 44, icon = "Interface\\Icons\\Spell_Shadow_ShadowBolt",           subText = "Rank 7" },
  },
  [46] = {
    { name = "Curse of the Elements",        school = "Affliction",  level = 46, icon = "Interface\\Icons\\Spell_Shadow_ChillTouch",    subText = "Rank 2" },
    { name = "Drain Life",                   school = "Affliction",  level = 46, icon = "Interface\\Icons\\Spell_Shadow_LifeDrain02",   subText = "Rank 5" },
    { name = "Life Tap",                     school = "Affliction",  level = 46, icon = "Interface\\Icons\\Spell_Shadow_BurningSpirit", subText = "Rank 5" },
    { name = "Banish",                       school = "Demonology",  level = 46, icon = "Interface\\Icons\\Spell_Shadow_Cripple",       subText = "Rank 2" },
    { name = "Create Healthstone (Greater)", school = "Demonology",  level = 46, icon = "Interface\\Icons\\INV_Stone_04",               subText = "" },
    { name = "Rain of Fire",                 school = "Destruction", level = 46, icon = "Interface\\Icons\\Spell_Shadow_RainOfFire",    subText = "Rank 3" },
    { name = "Soul Fire",                    school = "Destruction", level = 46, icon = "Interface\\Icons\\Spell_Fire_Fireball02",      subText = "Rank 3" },
  },
  [48] = {
    { name = "Curse of Agony", school = "Affliction",  level = 48, icon = "Interface\\Icons\\Spell_Shadow_CurseOfSargeras", subText = "Rank 5" },
    { name = "Siphon Life",    school = "Affliction",  level = 48, icon = "Interface\\Icons\\Spell_Shadow_Requiem",         subText = "Rank 3" },
    { name = "Conflagrate",    school = "Destruction", level = 48, icon = "Interface\\Icons\\Spell_Fire_Fireball",          subText = "Rank 2" },
    { name = "Shadowburn",     school = "Destruction", level = 48, icon = "Interface\\Icons\\Spell_Shadow_ScourgeBuild",    subText = "Rank 5" },
  },
  [50] = {
    { name = "Curse of Tongues",            school = "Affliction",  level = 50, icon = "Interface\\Icons\\Spell_Shadow_CurseOfTounges",     subText = "Rank 2" },
    { name = "Dark Harvest",                school = "Affliction",  level = 50, icon = "Interface\\Icons\\Spell_Shadow_SoulLeech",          subText = "Rank 2" },
    { name = "Death Coil",                  school = "Affliction",  level = 50, icon = "Interface\\Icons\\Spell_Shadow_DeathCoil",          subText = "Rank 2" },
    { name = "Create Soulstone (Greater)",  school = "Demonology",  level = 50, icon = "Interface\\Icons\\Spell_Shadow_SoulGem",            subText = "" },
    { name = "Demon Armor",                 school = "Demonology",  level = 50, icon = "Interface\\Icons\\Spell_Shadow_RagingScream",       subText = "Rank 6" },
    { name = "Detect Greater Invisibility", school = "Demonology",  level = 50, icon = "Interface\\Icons\\Spell_Shadow_DetectInvisibility", subText = "" },
    { name = "Mana Funnel",                 school = "Demonology",  level = 50, icon = "Interface\\Icons\\Spell_Shadow_UnsummonBuilding",   subText = "Rank 2" },
    { name = "Immolate",                    school = "Destruction", level = 50, icon = "Interface\\Icons\\Spell_Fire_Immolation",           subText = "Rank 6" },
    { name = "Searing Pain",                school = "Destruction", level = 50, icon = "Interface\\Icons\\Spell_Fire_SoulBurn",             subText = "Rank 5" },
  },
  [52] = {
    { name = "Drain Soul",        school = "Affliction",  level = 52, icon = "Interface\\Icons\\Spell_Shadow_Haunting",    subText = "Rank 4" },
    { name = "Create Spellstone", school = "Demonology",  level = 52, icon = "Interface\\Icons\\INV_Misc_Gem_Sapphire_01", subText = "" },
    { name = "Health Funnel",     school = "Demonology",  level = 52, icon = "Interface\\Icons\\Spell_Shadow_LifeDrain",   subText = "Rank 6" },
    { name = "Shadow Ward",       school = "Demonology",  level = 52, icon = "Interface\\Icons\\Spell_Shadow_AntiShadow",  subText = "Rank 3" },
    { name = "Shadow Bolt",       school = "Destruction", level = 52, icon = "Interface\\Icons\\Spell_Shadow_ShadowBolt",  subText = "Rank 8" },
  },
  [54] = {
    { name = "Corruption",     school = "Affliction",  level = 54, icon = "Interface\\Icons\\Spell_Shadow_AbominationExplosion", subText = "Rank 6" },
    { name = "Drain Life",     school = "Affliction",  level = 54, icon = "Interface\\Icons\\Spell_Shadow_LifeDrain02",          subText = "Rank 6" },
    { name = "Drain Mana",     school = "Affliction",  level = 54, icon = "Interface\\Icons\\Spell_Shadow_SiphonMana",           subText = "Rank 4" },
    { name = "Howl of Terror", school = "Affliction",  level = 54, icon = "Interface\\Icons\\Spell_Shadow_DeathScream",          subText = "Rank 2" },
    { name = "Conflagrate",    school = "Destruction", level = 54, icon = "Interface\\Icons\\Spell_Fire_Fireball",               subText = "Rank 3" },
    { name = "Hellfire",       school = "Destruction", level = 54, icon = "Interface\\Icons\\Spell_Fire_Incinerate",             subText = "Rank 3" },
    { name = "Soul Fire",      school = "Destruction", level = 54, icon = "Interface\\Icons\\Spell_Fire_Fireball02",             subText = "Rank 4" },
  },
  [56] = {
    { name = "Curse of Recklessness", school = "Affliction",  level = 56, icon = "Interface\\Icons\\Spell_Shadow_UnholyStrength", subText = "Rank 4" },
    { name = "Fear",                  school = "Affliction",  level = 56, icon = "Interface\\Icons\\Spell_Shadow_Possession",     subText = "Rank 3" },
    { name = "Life Tap",              school = "Affliction",  level = 56, icon = "Interface\\Icons\\Spell_Shadow_BurningSpirit",  subText = "Rank 6" },
    { name = "Shadowburn",            school = "Destruction", level = 56, icon = "Interface\\Icons\\Spell_Shadow_ScourgeBuild",   subText = "Rank 6" },
  },
  [58] = {
    { name = "Curse of Agony",             school = "Affliction",  level = 58, icon = "Interface\\Icons\\Spell_Shadow_CurseOfSargeras", subText = "Rank 6" },
    { name = "Death Coil",                 school = "Affliction",  level = 58, icon = "Interface\\Icons\\Spell_Shadow_DeathCoil",       subText = "Rank 3" },
    { name = "Siphon Life",                school = "Affliction",  level = 58, icon = "Interface\\Icons\\Spell_Shadow_Requiem",         subText = "Rank 4" },
    { name = "Create Healthstone (Major)", school = "Demonology",  level = 58, icon = "Interface\\Icons\\INV_Stone_04",                 subText = "" },
    { name = "Enslave Demon",              school = "Demonology",  level = 58, icon = "Interface\\Icons\\Spell_Shadow_EnslaveDemon",    subText = "Rank 3" },
    { name = "Rain of Fire",               school = "Destruction", level = 58, icon = "Interface\\Icons\\Spell_Shadow_RainOfFire",      subText = "Rank 4" },
    { name = "Searing Pain",               school = "Destruction", level = 58, icon = "Interface\\Icons\\Spell_Fire_SoulBurn",          subText = "Rank 6" },
  },
  [60] = {
    { name = "Curse of Doom",            school = "Affliction",  level = 60, icon = "Interface\\Icons\\Spell_Shadow_AuraOfDarkness",   subText = "" },
    { name = "Curse of Shadow",          school = "Affliction",  level = 60, icon = "Interface\\Icons\\Spell_Shadow_CurseOfAchimonde", subText = "Rank 2" },
    { name = "Curse of the Elements",    school = "Affliction",  level = 60, icon = "Interface\\Icons\\Spell_Shadow_ChillTouch",       subText = "Rank 3" },
    { name = "Dark Harvest",             school = "Affliction",  level = 60, icon = "Interface\\Icons\\Spell_Shadow_SoulLeech",        subText = "Rank 3" },
    { name = "Drain Soul",               school = "Affliction",  level = 60, icon = "Interface\\Icons\\Spell_Shadow_Haunting",         subText = "Rank 5" },
    { name = "Create Soulstone (Major)", school = "Demonology",  level = 60, icon = "Interface\\Icons\\Spell_Shadow_SoulGem",          subText = "" },
    { name = "Demon Armor",              school = "Demonology",  level = 60, icon = "Interface\\Icons\\Spell_Shadow_RagingScream",     subText = "Rank 7" },
    { name = "Health Funnel",            school = "Demonology",  level = 60, icon = "Interface\\Icons\\Spell_Shadow_LifeDrain",        subText = "Rank 7" },
    { name = "Conflagrate",              school = "Destruction", level = 60, icon = "Interface\\Icons\\Spell_Fire_Fireball",           subText = "Rank 4" },
    { name = "Immolate",                 school = "Destruction", level = 60, icon = "Interface\\Icons\\Spell_Fire_Immolation",         subText = "Rank 7" },
    { name = "Shadow Bolt",              school = "Destruction", level = 60, icon = "Interface\\Icons\\Spell_Shadow_ShadowBolt",       subText = "Rank 9" },
  },
}